# Generated by Django 5.2.1 on 2026-01-29 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_referral_code_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('game', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_testimonial',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='betting_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bet amount allowed (for Users)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coins this user can transfer (for Masters)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('master', 'Master'), ('super_admin', 'Super Admin'), ('powerhouse', 'PowerHouse')], default='user', max_length=20),
        ),
    ]
