# Generated by Django 5.2.1 on 2026-01-30 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_user_betting_limit_user_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('bonus_type', models.CharField(choices=[('welcome', 'Welcome'), ('deposit', 'Deposit'), ('referral', 'Referral'), ('cashback', 'Cashback'), ('other', 'Other')], default='other', max_length=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wagering_requirement', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_uses', models.IntegerField(default=0)),
                ('uses_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_promo_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemption', to='core.bonus')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_promo_code_redemption',
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
