# Generated by Django 5.2.1 on 2026-02-04 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_min_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('AVAILABLE', 'Available'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Chat Message',
                'verbose_name_plural': 'Live Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='core_livech_sender__1e7e8d_idx'), models.Index(fields=['receiver', 'sender'], name='core_livech_receive_6d20cb_idx')],
            },
        ),
    ]
