# Generated by Django 5.2.1 on 2026-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_live_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='provider_game_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Provider game identifier (hash) for launch URL', max_length=64),
        ),
        migrations.AddField(
            model_name='gameprovider',
            name='api_secret',
            field=models.CharField(blank=True, help_text='Secret for AES encryption with provider', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_game_uid__gt', '')), fields=('provider', 'provider_game_uid'), name='unique_provider_game_uid'),
        ),
    ]
