# Generated by Django 5.2.1 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_provider_game_uid_and_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprovider',
            name='api_token',
            field=models.CharField(blank=True, help_text='Fixed token sent in launch payload; provider may use for callbacks', max_length=255),
        ),
    ]
