# Generated by Django 6.0.2 on 2026-03-24 04:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_reject_suggestions_withdraw_tx_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersetting',
            name='reject_reason_suggestions',
            field=models.JSONField(blank=True, default=core.models.default_reject_reason_suggestions),
        ),
    ]
