from django.urls import path
from core.views.powerhouse import (
    dashboard_views,
    user_views,
    deposit_views,
    withdraw_views,
    kyc_views,
    game_log_views,
    transaction_views,
    activity_views,
    game_views,
    super_setting_views,
    site_setting_views,
    cms_views,
    testimonial_views,
    message_views,
    bonus_rule_views,
)

urlpatterns = [
    path('dashboard/', dashboard_views.dashboard),
    path('supers/', user_views.user_list_supers),
    path('supers/<int:pk>/', user_views.user_detail_supers),
    path('supers/create/', user_views.user_create_super),
    path('supers/<int:pk>/edit/', user_views.user_update_super),
    path('supers/<int:pk>/delete/', user_views.user_delete_super),
    path('supers/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_super),
    path('supers/<int:pk>/reset-password/', user_views.user_reset_password_super),
    path('masters/', user_views.user_list_masters),
    path('masters/<int:pk>/', user_views.user_detail_masters),
    path('masters/create/', user_views.user_create_master),
    path('masters/<int:pk>/edit/', user_views.user_update_master),
    path('masters/<int:pk>/delete/', user_views.user_delete_master),
    path('masters/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_master),
    path('masters/<int:pk>/reset-password/', user_views.user_reset_password_master),
    path('players/', user_views.user_list_players),
    path('players/<int:pk>/', user_views.user_detail_players),
    path('players/create/', user_views.user_create_player),
    path('players/<int:pk>/edit/', user_views.user_update_player),
    path('players/<int:pk>/delete/', user_views.user_delete_player),
    path('players/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_player),
    path('players/<int:pk>/reset-password/', user_views.user_reset_password_player),
    path('deposits/', deposit_views.deposit_list),
    path('deposits/create/', deposit_views.deposit_create),
    path('deposits/direct/', deposit_views.deposit_direct),
    path('deposits/payment-modes/', deposit_views.deposit_payment_modes),
    path('deposits/<int:pk>/', deposit_views.deposit_detail),
    path('deposits/<int:pk>/approve/', deposit_views.deposit_approve),
    path('deposits/<int:pk>/reject/', deposit_views.deposit_reject),
    path('withdrawals/', withdraw_views.withdraw_list),
    path('withdrawals/direct/', withdraw_views.withdraw_direct),
    path('withdrawals/<int:pk>/', withdraw_views.withdraw_detail),
    path('withdrawals/<int:pk>/approve/', withdraw_views.withdraw_approve),
    path('withdrawals/<int:pk>/reject/', withdraw_views.withdraw_reject),
    path('kyc/', kyc_views.kyc_list),
    path('kyc/<int:pk>/approve/', kyc_views.kyc_approve),
    path('kyc/<int:pk>/reject/', kyc_views.kyc_reject),
    path('game-log/', game_log_views.game_log_list),
    path('transactions/', transaction_views.transaction_list),
    path('activity/', activity_views.activity_list),
    path('categories/', game_views.category_list_create),
    path('categories/<int:pk>/', game_views.category_detail),
    path('providers/', game_views.provider_list_create),
    path('providers/<int:pk>/', game_views.provider_detail),
    path('games/', game_views.game_list_create),
    path('games/<int:pk>/', game_views.game_detail),
    path('bonus-rules/', bonus_rule_views.bonus_rule_list_create),
    path('bonus-rules/<int:pk>/', bonus_rule_views.bonus_rule_detail),
    path('super-settings/', super_setting_views.super_setting_get),
    path('super-settings/save/', super_setting_views.super_setting_save),
    path('site-settings/', site_setting_views.site_setting_get),
    path('site-settings/update/', site_setting_views.site_setting_update),
    path('cms/', cms_views.cms_list_create),
    path('cms/<int:pk>/', cms_views.cms_detail),
    path('testimonials/', testimonial_views.testimonial_list_create),
    path('testimonials/<int:pk>/', testimonial_views.testimonial_detail),
    path('messages/', message_views.message_list),
    path('messages/send/', message_views.message_create),
]
